# See https://rust-lang.github.io/rustfmt/ for all possible settings & documentation.

# When running `cargo fmt`, we don't need to set this option because it will be picked up from cargo. However, this
# explicit setting is useful for (IDE) tools that run `rustfmt` directly, which otherwise defaults to "2015".
edition = "2024"

max_width = 100
# hard_tabs = true # I assume we use soft tabs?
tab_spaces = 4
newline_style = "Unix"

use_field_init_shorthand = true

# enable unstable features; only available with nightly rust ðŸ¥²
unstable_features = true
comment_width = 120
wrap_comments = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
