# based on https://bevyengine.org/learn/book/getting-started/setup/#enable-fast-compiles-optional
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-Clink-arg=-fuse-ld=mold", "-Zshare-generics=y", "-Zthreads=0"]
